# Generated by Django 4.1.7 on 2023-03-31 21:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_conversation_messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='summary_conversation',
            field=models.CharField(default='', max_length=250),
        ),
    ]
