# Generated by Django 4.1.7 on 2023-04-01 06:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_profile_current_conversation_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_conversation_messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default='Start a conversation and keep it up, by asking questions related to every new message and every previous message, pretend to be a best friend.'), blank=True, default=list, size=None),
        ),
    ]
