# Generated by Django 4.1.7 on 2023-04-01 06:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_profile_current_conversation_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_conversation_messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
    ]
