# Generated by Django 4.1.7 on 2023-04-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_alter_profile_current_conversation_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='summary_conversation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
